server:
  port: 8443
  ssl:
    key-store: D:\Projects\SpringProjects\taco-cloud\mykeys.jks
    key-store-password: 123123
    key-password: 123123

spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE;
    username: sam
    password: sam
  profiles:
    active:
      - prod

taco:
  orders:
    pageSize: 10



